# Generated by Django 2.2.14 on 2020-07-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200717_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoproducts',
            name='photo',
            field=models.ImageField(null=True, upload_to='photosproduct'),
        ),
    ]
