# Generated by Django 2.2.14 on 2020-07-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200717_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_banner', models.ImageField(null=True, upload_to='banners')),
                ('category', models.ForeignKey(help_text='Категория продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_category', to='core.Category')),
                ('product', models.ForeignKey(help_text='Продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_product', to='core.Products')),
            ],
            options={
                'verbose_name': 'Банеры',
                'verbose_name_plural': 'Банер',
            },
        ),
    ]
