# Generated by Django 2.2.9 on 2020-08-03 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_coockie', models.CharField(max_length=255, null=True)),
                ('product', models.ForeignKey(help_text='Продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_product', to='core.Products')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
