# Generated by Django 2.2.9 on 2020-08-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orders_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Гостевой юзер',
                'verbose_name_plural': 'Гостевые юзеры',
            },
        ),
    ]
