# Generated by Django 2.2.9 on 2020-08-11 07:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_guestuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqistrationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Заказы', size=None, verbose_name='Заказы')),
                ('sum', models.FloatField(default=0, null=True)),
                ('address', models.TextField(null=True)),
                ('contact_phone', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('full_name', models.TextField(null=True)),
                ('date_registration', models.DateTimeField(null=True)),
                ('isDecoration', models.BooleanField(default=False)),
                ('user_coockie', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Оформленый заказ',
                'verbose_name_plural': 'Оформленные заказы',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
